[package]
name = "ckb-debugger-binaries"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
autobins = false

[[bin]]
name = "ckb-debugger"
path = "src/main.rs"

[dependencies]
clap = "2.33.0"
ckb-script = { git = "https://github.com/jjyr/ckb", rev = "0386399", default-features = false, features = ["detect-asm"] }
ckb-sdk-types = { git = "https://github.com/jjyr/ckb-cli", rev = "f53ef01", default-features = false, features = ["detect-asm"] }
ckb-standalone-debugger = { path = ".." }
ckb-types = { git = "https://github.com/jjyr/ckb", rev = "0386399" }
ckb-vm = { git = "https://github.com/xxuejie/ckb-vm", rev = "6381a18", features = ["detect-asm"] }
ckb-vm-debug-utils = { git = "https://github.com/jjyr/ckb-vm-debug-utils", rev = "91a49ca" }
env_logger = "0.4.3"
faster-hex = "0.4.0"
gdb-remote-protocol = { git = "https://github.com/luser/rust-gdb-remote-protocol", rev = "565ab0c" }
log = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_plain = "0.3.0"
